service:
  type: LoadBalancer
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: [HTTP/1.1, HTTP/2]
      valid_status_codes: []  # Defaults to 2xx
      fail_if_ssl: false
      tls_config:
        insecure_skip_verify: true  # Set to true to skip SSL certificate verification