server:
  service:
    enabled: true
    type: LoadBalancer
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'mail_ionos'
        metrics_path: / 
        static_configs:
          - targets:
            - mail.ionos.com:80
   